name: ys_media_player_pro
description: "YS Media Player Pro â€“ MX Player + KM Player level hybrid media engine"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

#######################
#   MAIN DEPENDENCIES #
#######################
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  # --- ROUTING ---
  go_router: ^17.0.0

  # --- DATABASE ---
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # --- STORAGE & PERMISSIONS ---
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  # --- MEDIA LIBRARY ---
  photo_manager: ^3.8.0
  video_thumbnail: ^0.5.6

  # --- PREFS / CACHE ---
  shared_preferences: ^2.5.3

  # --- AUDIO SESSION ---
  audio_session: ^0.2.2

  # --- NOTIFICATIONS ---
  flutter_local_notifications: ^19.5.0

  # --- DOWNLOADS ---
  dio: ^5.9.0

  # --- TELEMETRY / FEEDBACK / CRASH ---
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.4
  crypto: ^3.0.5

  # --- LOCALIZATION (DAY 16) ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # --- ICONS / SVG ---
  flutter_svg: ^2.0.10

  # --- QUICK ACTIONS ---
  quick_actions: ^1.0.5

#######################
#   DEV DEPENDENCIES  #
#######################
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

#######################
#     FLUTTER ASSETS  #
#######################
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/i18n/

  fonts:
    - family: YSIcons
      fonts:
        - asset: assets/icons/ysicons.ttf
